apiVersion: v1
kind: Service
metadata:
  name: litecoin
  labels:
    app: litecoin
spec:
  ports:
  - port: 9332
    name: litecoin-9332
  - port: 9333
    name: litecoin-9333
  - port: 19332
    name: litecoin-19332
  - port: 19333
    name: litecoin-19333
  - port: 19444
    name: litecoin-19444
  clusterIP: None
  selector:
    app: litecoin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: litecoin # has to match .spec.template.metadata.labels
  serviceName: "litecoin"
  replicas: 1
  template:
    metadata:
      labels:
        app: litecoin
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: litecoin
        image: docker.io/burninmedia/litecoin:0.0.3
        ports:
        - containerPort: 9332
          name: litecoin-9332
        - containerPort: 9333
          name: litecoin-9333
        - containerPort: 19332
          name: litecoin-19332
        - containerPort: 19333
          name: litecoin-19333
        - containerPort: 19444
          name: litecoin-19444
        volumeMounts:
        - name: litecoin-data
          mountPath: /home/litecoin/.litecoin
      resources:
        requests:
          memory: 256Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "1000m"
  volumeClaimTemplates:
  - metadata:
      name: litecoin-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "litecoin-storage-class"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litecoin-data
spec:
  storageClassName: "litecoin-data" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: litecoin-pv